### ISSUE TITLE
Removing VAT from inputted item

### ISSUE THREAD

**Issue by deanpcmad** [ianmurrays/active_invoices#3]
I would like to be able to input a price which includes VAT/tax and it calculates and removes the VAT from that amount.
How would I go about doing this?
Thanks, Dean

**Comment by ianmurrays** [comment]
Hmm you'd need to add a boolean to the invoice_item model and check it when you calculate the invoices total, as to remove the VAT from that item.

That's how I'd do it at least :D

**Comment by deanpcmad** [comment]
OK thanks, I'm quite new to Rails, would you be able to show the code needed?
I would like to input an amount with VAT (e.g. £120), then when submitting it, it shows the amount without VAT (£100) and also adds the VAT (£20) on the end of the invoice to the total.
Thanks

**Comment by ianmurrays** [comment]
Sorry, can't show the code since I don't really have the time :(. But what you need is just a matter of modifying the code that calculates the invoice's total.  

Cheers!  

--Ian Murray
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by deanpcmad** [comment]
OK no probs. I shall have a go and see what I can do :)

**Comment by deanpcmad** [comment]
I've managed to do it. If you or anyone else is interested, here is the code - https://github.com/deanperry/active_invoices
