### ISSUE TITLE
add item

### ISSUE THREAD

**Issue by sergiobortsov** [ianmurrays/active_invoices#8]
Hi! Sorry, but I'm not strong in Ruby yet, so can't understand how to add Item in invoice. When I create new invoice and click Add item nothing happened (in logs too).
I'll be grateful for help.

**Comment by ianmurrays** [comment]
Are you sure you're not getting a javascript error?

**Comment by sergiobortsov** [comment]
Firebug said about ReferenceError: $ is not defined. But in rails logs - nothing. And active_admin.js just empty. Where is mistake? )) Thanks.

**Comment by ianmurrays** [comment]
Looks like jQuery isn't getting loaded for some reason. Have you modified anything?

**Comment by sergiobortsov** [comment]
No. I just made steps from your README.

**Comment by sergiobortsov** [comment]
Thanks. Fixed by rails version upgrade.
