### ISSUE TITLE
Is there a good way to calculate the totals while adding Items?

### ISSUE THREAD

**Issue by demogar** [ianmurrays/active_invoices#9]
Hi there.

Is there a good way to actually calculate the totals (subtotals, taxes, discounts, totals) while adding and modifying the items?

This is really easy to do with regular Rails, but I have no idea how to do this with ActiveAdmin. I guess there should be a "simple" way to make this work.

Thanks in advance!

**Comment by ianmurrays** [comment]
You mean with javascript?

**Comment by demogar** [comment]
@ianmurrays yup. Just need some guidance. I think that it would be probably a good idea to show the totals while adding items.

Any guidance is more than appreciated.

**Comment by ianmurrays** [comment]
Unfortunately I haven't worked with this gem (active_admin) for years now, so I don't really know how to add javascript to the views. :(

**Comment by demogar** [comment]
Ok, then. I'll try to see how I can actually implement this on my own. If I'm lucky, I'll put a PR.

We can close this ticket for now.

Cheers!
